### ISSUE TITLE
arduino IDE

### ISSUE THREAD

**Issue by Oegtsgeest** [Rotario/arduinoCurveFitting#1]
Hi,
Nice work, but it does not compile with Arduino IDE. Get all kind of errors:
printf for instance. These are relatively easy to overcome.

More serious are the errors in the ccp file eg: double T[maxOrder] = {0}; //Values to generate RHS of linear equation
etc

Any solution? Thankyo in advance

**Comment by Rotario** [comment]
Hi,
I've not tested this on Arduino! My fault, I probably should.
I've changed the serial printfs in  5a217d0fac0a7385be93224e2b932e85160f8b92
I'll test the other stuff now

**Comment by Rotario** [comment]
This should be fixed in v1.0.3

Please update your library and see if that works!
Thanks,
Rowan
